default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: GreatControl_development

test:
  <<: *default
  database: GreatControl_test

production:
  <<: *default
  database: GreatControl_production
  username: GreatControl
  password: <%= ENV['GREATCONTROL_DATABASE_PASSWORD'] %>
